---
kind: Service
apiVersion: v1
metadata:
  name: helloweb-service
spec:
  type: NodePort
  selector:
    app: helloweb
    component: web
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: helloweb
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloweb
      component: web
  template:
    metadata:
      labels:
        app: helloweb
        component: web
    spec:
      containers:
      - name: helloweb
        image: quay.io/joerx/helloweb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
